from db.connect import connectDb
con = connectDb()
cur = con.cursor()
cur.execute("SELECT id, name FROM recipe WHERE name LIKE '%Chicken%' LIMIT 5")
print("Chicken:", cur.fetchall())
cur.execute("SELECT id, name FROM recipe WHERE name LIKE '%Fish%' LIMIT 5")
print("Fish:", cur.fetchall())
cur.execute("SELECT id, name FROM recipe WHERE name LIKE '%Mutton%' LIMIT 5")
print("Mutton:", cur.fetchall())
cur.execute("SELECT id, name FROM recipe WHERE name LIKE '%Beef%' LIMIT 5")
print("Beef:", cur.fetchall())
cur.execute("SELECT id, name FROM recipe WHERE name LIKE '%Pork%' LIMIT 5")
print("Pork:", cur.fetchall())
cur.execute("SELECT COUNT(*) FROM recipe WHERE name LIKE '%Chicken%'")
print("Chicken count:", cur.fetchone())
